### ISSUE TITLE
Copying tab links doesn't work

### ISSUE THREAD

**Issue by TigerCat-hu** [wingovers/Tabby#1]
Copying tab links doesn't work, just the title for me. I do something wrong? Thanks!

**Comment by wingovers** [comment]
Sorry to hear that. Where are you pasting it? Maybe I can work on a fix for
that app.

The extension puts a line of HTML into the pasteboard with the page title
and its link, along with a bullet point. That last bit renders in word but
not in other apps.

Ryan

**Comment by TigerCat-hu** [comment]
Hi, no problem!
:-)

I want to paste a simple text editor...

**Comment by wingovers** [comment]
Gotcha.  What’s the name of the editor you want to use?

I use Typora and it works, but could see how another editor wouldn’t work.

Ryan

**Comment by TigerCat-hu** [comment]
macOS text editor. It's simple, i love it. :-)

**Comment by wingovers** [comment]
Yes, it is. Here’s a short-term and medium-term plan:

In Text Editor, you can hit Shift + Command + T to change to Rich Text. Then the HTML links will paste as you’d hoped. But I assume you want to stay in Plain Text mode. Therefore...

In the next few days, I’ll update the extension to add a new plain text representation of links to the clipboard. That should let you stay in Plain Text mode in Text Editor. Each tab will get three lines: title, http://…., and a blank line as a spacer for the next item. Even though it’s a small change, it may take me and the Apple Store a few days turnaround given WWDC this week. Sound good?

Ryan

**Comment by TigerCat-hu** [comment]
I think it will be okay, thank you very much!
:-)

**Comment by wingovers** [comment]
The update is now on the App Store to work with plain text editors.

**Comment by TigerCat-hu** [comment]
Thanks!
